export enum RelOp {
  nop = "NOP",
  like = "ENTHÄLT",
  notlike = "ENTHÄLT NICHT",
  equal = "GLEICH",
  notequal = "UNGLEICH",
  startswith = "BEGINNT MIT",
  endswith = "ENDED MIT",
  inlist = " GLEICH",
  notinlist = " UNGLEICH",
  inlistA = "GLEICH ",
  notinlistA = "UNGLEICH ",
  exist = "VORHANDEN",
  notexist = "NICHT VORHANDEN",
  equalNum = "GLEICH",
  notequalNum = "UNGLEICH",
  gtNum = "GRÖSSER ALS",
  ltNum = "KLEINER ALS",
  equalDat = "GLEICH",
  notequalDat = "UNGLEICH",
  gtDat = "GRÖSSER ALS",
  ltDat = "KLEINER ALS",
}
